language: node_js

node_js:
  - "9"

before_script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "dist"
  on:
    branch: master

notifications:
  email: false

cache: yarn
